jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:TaskMasterAccessSecret2026SuperLongKey}
    expiration: ${JWT_ACCESS_EXPIRATON:900000}
  refresh:
    secret: ${JWT_REFRESH_SECRET:TaskMasterRefreshSecret2026SuperLongKey}
    expiration: ${JWT_REFRESH_EXPIRATON:604800000}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8082}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8090}

app-url: ${APP_URL:http://localhost:3000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-db:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: Auth-service

logging:
  level:
    com.slavacom.auth_service: INFO
    org.springframework.security: INFO

