server:
  port: ${SERVER_PORT:8080}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:TaskMasterAccessSecret2026SuperLongKey}
  refresh:
    secret: ${JWT_REFRESH_SECRET:TaskMasterRefreshSecret2026SuperLongKey}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8091}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8092}
          predicates:
            - Path=/api/users/**

        - id: user-service-profiles
          uri: ${USER_SERVICE_URL:http://localhost:8092}
          predicates:
            - Path=/api/profiles/**

        - id: organization-service
          uri: ${ORG_SERVICE_URL:http://localhost:8093}
          predicates:
            - Path=/api/organizations/**

        - id: organization-service-projects
          uri: ${ORG_SERVICE_URL:http://localhost:8093}
          predicates:
            - Path=/api/projects/**

        - id: organization-service-tags
          uri: ${ORG_SERVICE_URL:http://localhost:8093}
          predicates:
            - Path=/api/tags/**

        - id: task-service
          uri: ${TASK_SERVICE_URL:http://localhost:8094}
          predicates:
            - Path=/api/tasks/**

        - id: task-service-comments
          uri: ${TASK_SERVICE_URL:http://localhost:8094}
          predicates:
            - Path=/api/comments/**

        - id: task-service-attachments
          uri: ${TASK_SERVICE_URL:http://localhost:8094}
          predicates:
            - Path=/api/attachments/**