server:
  port: ${SERVER_PORT:8080}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:TaskMasterAccessSecret2026SuperLongKey}
  refresh:
    secret: ${JWT_REFRESH_SECRET:TaskMasterRefreshSecret2026SuperLongKey}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8080}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8080}
          predicates:
            - Path=/api/users/**,

        - id: user-service-profiles
          uri: ${USER_SERVICE_URL:http://user-service:8080}
          predicates:
            - Path=/api/profiles/**

        - id: organization-service
          uri: ${ORG_SERVICE_URL:http://organization-service:8080}
          predicates:
            - Path=/api/organizations/**

        - id: organization-service-projects
          uri: ${ORG_SERVICE_URL:http://organization-service:8080}
          predicates:
            - Path=/api/projects/**

        - id: organization-service-tags
          uri: ${ORG_SERVICE_URL:http://organization-service:8080}
          predicates:
            - Path=/api/tags/**

        - id: task-service
          uri: ${TASK_SERVICE_URL:http://task-service:8080}
          predicates:
            - Path=/api/tasks/**
