spring:
  application:
    name: NotificationService

  # Distributed Tracing with Sleuth + Zipkin
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
    sender:
      type: web
  sleuth:
    sampler:
      probability: ${SLEUTH_SAMPLING_RATE:1.0}
    trace-id128: true

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:your@gmail.com}
    password: ${SMTP_PASSWORD:app-password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notification-service-group
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.slavacom.notificationservice.event
        spring.json.value.default.type: com.slavacom.notificationservice.event.NotificationEvent

    listener:
      ack-mode: record

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}


telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:your-telegram-bot-token}

server:
  port: ${SERVER_PORT:8089}

logging:
  level:
    root: INFO
    com.slavacom.notificationservice: DEBUG
    org.springframework.cloud.sleuth: DEBUG
