include:
  - docker-compose.db.yml
  - docker-compose.kafka.yml
  - docker-compose.services.yml

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - JAVA_OPTS=-Xms256m -Xmx256m
    networks:
      - micro-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  micro-net:
    name: micro-net
    driver: bridge

volumes:
  auth-db-data:
  user-db-data:
  task-db-data:
  event-db-data:
  organization-db-data:
  permission-db-data:
  redis-data: