services:

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

  organization-db:
    image: postgres:16
    container_name: organization-db
    environment:
      POSTGRES_DB: organization_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - organization-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

  task-db:
    image: postgres:16
    container_name: task-db
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - task-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

  event-db:
    image: postgres:16
    container_name: event-db
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - event-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

  redis:
    image: redis:8.6.2
    restart: always
    ports:
      - "6379:6379"
    networks:
      - micro-net
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
