services:
  gateway-service:
    build: ../Gateway-service
    container_name: TaskMaster-GatewayService
    depends_on:
      - auth-service
      - user-service
      - organization-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: mySuperSecretKeyForDockerEnvironment
      AUTH_SERVICE_URL: http://auth-service:8080
      USER_SERVICE_URL: http://user-service:8080
      ORG_SERVICE_URL: http://organization-service:8080
      TASK_SERVICE_URL: http://task-service:8080
    ports:
      - "8080:8080"
    networks:
      - micro-net

  auth-service:
    build: ../Auth-service
    image: task-master.auth-service:latest

    container_name: TaskMaster-AuthService
    restart: always
#    depends_on:
#      - auth-db
#      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      USER_SERVICE_URL: http://user-service:8080
      JWT_SECRET: mySuperSecretKeyForDockerEnvironment
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8080"
    networks:
      - micro-net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  user-service:
    build: ../UserService
    container_name: TaskMaster-UserService
    ports:
      - "8082:8080"
    depends_on:
      - user-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PROFILE_SERVICE_URL: http://user-service:8080
    volumes:
      - user-service-logs:/app/logs
    networks:
      - micro-net

  organization-service:
    build: ../OrganizationService
    container_name: TaskMaster-OrganizationService
    ports:
      - "8083:8080"
    depends_on:
      - organization-db
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://organization-db:5432/organization_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PROFILE_SERVICE_URL: http://user-service:8080
      USER_SERVICE_URL: http://user-service:8080

    networks:
      - micro-net



volumes:
  user-service-logs:
    driver: local

