spring:
    application:
        name: OrganizationService

    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/organization_db}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8092}
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8091}

server:
  port: ${SERVER_PORT:8080}

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_RATE:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    root: INFO
    com.slavacom.organizationservice: DEBUG
    io.micrometer.tracing: DEBUG